[build]
command = "yarn build"
publish = "dist"

[[redirects]]
from = "https://saejinmh.com/*"
to = "https://saejinheinert.com/:splat"
status = 301
force = true

[[redirects]]
from = "https://saejinheinert.netlify.app/*"
to = "https://saejinheinert.com/:splat"
status = 301
force = true
